#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {1.2-eap,1.2.70-eap,1.2.70-eap-jdk10,1.2.70-eap-4,1.2.70-eap-4-jdk10}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
