#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {1.3.50-eap-slim,1.3.50-eap-54-slim,1.3.50-eap-jdk11-slim,1.3.50-eap-54-jdk11-slim}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
