#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {jdk12-alpine,1-jdk12-alpine,1.3.21-jdk12-alpine}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done

for tag in {jdk12,1-jdk12,1.3-jdk12,1.3.21-jdk12}; do
    docker tag $IMAGE_NAME zenika/alpine-kotlin:${tag}
    docker push zenika/alpine-kotlin:${tag}
done
