#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {1.3.0-jdk8-alpine,1.3-alpine,1.3.0-alpine,1.3-rc-146-alpine,1.3.0-rc-146-alpine,1.3-rc-146-jdk8-alpine,1.3.0-rc-146-jdk8-alpine}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done

for tag in {1.3,1.3-jdk8,1.3.0,1.3.0-jdk8,1.3-rc-146,1.3.0-rc-146,1.3-rc-146-jdk8,1.3.0-rc-146-jdk8}; do
    docker tag $IMAGE_NAME zenika/alpine-kotlin:${tag}
    docker push zenika/alpine-kotlin:${tag}
done
