#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {slim,1-slim,1.3-slim,1.3.21-slim,jdk11-slim,1-jdk11-slim,1.3.21-jdk11-slim}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
