#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {jdk8,1-jdk8,1.3.0-jdk8}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
