#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {1.3.0-jdk10,1.3,1.3.0,1.3-rc-190,1.3.0-rc-190,1.3-rc-190-jdk10,1.3.0-rc-190-jdk10}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
