#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {1.3.0-jdk10-slim,1.3-slim,1.3.0-slim,1.3-rc-116-slim,1.3.0-rc-116-slim,1.3-rc-116-jdk10-slim,1.3.0-rc-116-jdk10-slim}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
