#!/bin/bash
set -e

tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

for tag in {jdk10-slim,1-jdk10-slim,1.3.50-jdk10-slim}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done
